server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
    - job_name: nginx
      static_configs:
        - targets:
            - localhost
          labels:
            job: nginx
            agent: promtail
            __path__: /var/log/nginx/json-access.log

      pipeline_stages:
        - json:
            expressions:
              address: address
              user_agent: user_agent
              status: status
        - labels:
            address: address
            user_agent: user_agent
            status: status